### PR TITLE
Fix issue where collection is being ignored since it implements Arryable

### PR DESCRIPTION
**Pull request by VinceG**

### CODE REVIEW

**Comment by VinceG** [comment]
@crynobone Hoping this can be merged into the 5.6 branch and get tagged so we can use it now instead of waiting for Laravel 5.7 which will take months.

Thank You.

**Comment by crynobone** [comment]
I already merge the code in 5.6, what surprises me is that the added tests is still passing without swapping then code.

**Comment by VinceG** [comment]
@crynobone Perfect, Thank You. Is it going to be tagged? 5.6.1? instead of using the branch name in composer.

Thanks again.

**Comment by crynobone** [comment]
As I commented, the tests doesn't fail without changing the code, don't see the rush the release right now

**Comment by VinceG** [comment]
The test I added fails if you undo the change to the Selection class. This is indeed a bug in the code 

-----
Vincent Gabriel
Software Engineer

Please excuse my brevity, sent from my iPhone

**Comment by crynobone** [comment]
Released https://github.com/laravie/html/releases/tag/v5.6.1

**Pull request closed without merging**
